language: node_js
node_js:
    - "node"
    - "lts/*"
    - "8"
script:
    - yarn run format:check
    - yarn run lint
    - yarn run test
    - yarn run build
after_success: bash <(curl -s https://codecov.io/bash)
